### ISSUE TITLE
0402CS-16NX_LU footprint conflict

### ISSUE THREAD

**Issue by TheaperDeng** [wisp/wisp5-hw#4]
I’m working on make a sample of Wisp5 and I found a problem. 

On the bom table, L1 has its Manufacturer Part Number as 0402CS-16NX_LU, which is 0402 packaging. And on the PCB board file, it has footprint as 0603. How should I solve this conflict?

**Comment by ghost** [comment]
Hi TheaperDeng,

Good catch. 

Sometimes larger footprints are used to allow easier hand soldering/rework, or to allow either size (0603 or 0402) parts to be populated. It is very likely that the 0402 device can be populated on the slightly larger 0603 footprint without any issues. You can contact your PCB assembler to confirm that they will not have an issue with this.

Best luck,
Aaron
